rework center to GPS functionality
MerginMaps/input pull request #2614
Opened 2023-03-06 15:59 UTC by alexbruy

- do not center to GPS position when switching between view and digitizing
 - add follow GPS mode when map follows GPS position

2023-03-13 15:22 UTC, tomasMizera requested changes

2023-03-13 16:19 UTC, alexbruy commented on app/qml/map/MapCanvas.qml
> +      userInteractedWithMap()
If you say so

2023-03-23 09:20 UTC, tomasMizera commented on app/qml/main.qml
> +        onMyLocationClicked: {
@alexbruy for the sake of keeping the UX same as before, can you also add a slot for `onMyLocationHold` that would do exactly the same as `onMyLocationClicked`? Thanks!

2023-03-23 09:20 UTC, tomasMizera commented on app/qml/map/RecordingTools.qml
> -        mapTool.recordingType = RecordingMapTool.Manual
Let's keep the `else` branch here so that it is possible to exit the streaming mode

2023-03-24 12:40 UTC, tomasMizera approved these changes
Let's proceed with testing :)

2023-04-03 16:33 UTC, tomasMizera commented
#861me5mj1

2023-06-05 13:55 UTC, PeterPetrik commented
@alexbruy can you please check to merge to dev-2.3 and rebase? thanks

2023-08-31 07:21 UTC, tomasMizera commented
This is stale for too long now, I will cherry-pick some changes and create a new PR

2023-08-31 07:21 UTC, closed without merging